#!/bin/bash

# CAUTION! keep the config script clean!
# mostly alphabetical, but only  if there is no technical or logical depencies
# and if so then add an empty line

# projekt global settings - name of the game :-) as strings

# don't downgrade tsc-levels, only upgrade tsc-levels 
# bc. there is no real backward compatibilty, update always the tsc_write_env() and bellow

# PRJG = project global settings - name of the game :-) as strings

# only the same level are compatible
TSC_PRJG_LEVEL="2"

# "1"=debug on "0"=debug off
TSC_DEBUG="1"

TSC_PRJG_COPYR="Copyright: Kaiserrundfunk.com / Jonacast 2019-2025"
TSC_PRJG_DEDIT="Created by TS-Config with ./configure.sh before any compiling should happen - do not edit this file"

# SYS = system depended - hint: the sorting of uname is like the manpage uname --help

TSC_SYS_ALL=`uname -a`
TSC_SYS_OPNS=`uname -s`
TSC_SYS_NODE=`uname -n`
TSC_SYS_OPREL=`uname -r`
TSC_SYS_OPVER=`uname -v`
TSC_SYS_ARCH=`uname -m`
TSC_SYS_CPU=`uname -p`
TSC_SYS_HARDW=`uname -i`
TSC_SYS_OPNL=`uname -o`

	if [[ $TSC_SYS_OPNL == "GNU/Linux" ]]
	then
		TSC_SLASH="/"
	fi
	
	if [[ $TSC_SYS_OPNL == "Cygwin" ]]
	then
		TSC_SLASH="/"
	fi

TSC_PRJG_TS=`date "+%d.%m.%Y %H:%M:%S" `
TSC_PRJG_TS_S=\"$TSC_PRJG_TS\"

TSC_PRJG_COMP="$TSC_SYS_OPNS ($TSC_SYS_NODE) $TSC_SYS_HARDW at $TSC_PRJG_TS"
TSC_PRJG_COMP_S=\""$TSC_PRJG_COMP"\"

TSC_PRJG_FNAME="offlinecrypto"
TSC_PRJG_PNAME="Offlinecrypto"
TSC_PRJG_PSUMS="A tool for offline cryptos against blackouts and hyperinflation"
TSC_PRJG_PSUML="A tool for offline cryptos against blackouts and hyperinflation"
TSC_PRJG_PGRP="Applications/Productivity"
TSC_PRJG_PLIC="MIT"

TSC_PRJG_LANG_DE="de"
TSC_PRJG_LANG_EN="en"
TSC_PRJG_LANG=$TSC_PRJG_LANG_DE
TSC_DBG_LANG=$TSC_PRJG_LANG_DE
TSC_LOG_LANG=$TSC_PRJG_LANG_DE

# [?,0]=major [?,1]=minor [?,2]=release [?,3]=patch [?,4]=version 
# [?,5]=directoy [?,6]=Label [?,7]=snapcraft grade [?,8]=snapcraft confinement
declare -A TSC_PRJG_VERSION=(
[0,0]="0" 
[0,1]="1"
[0,2]="0"
[0,3]="1"

[1,0]="0"
[1,1]="1"
[1,2]="1"
[1,3]="1"

[2,0]="0"
[2,1]="1"
[2,2]="2"
[2,3]="1"

[0,4]=""
[1,4]="" 
[2,4]=""

[0,5]="develop"
[0,6]="DEVELOP"
[0,7]="devel"
[0,8]="devmode"

[1,5]="testing"
[1,6]="TESTING"
[1,7]="devel"
[1,8]="devmode"

[2,5]="stable"
[2,6]="STABLE"
[2,7]="stable"
[2,8]="devmode"

)
TSC_PRJG_VERSION[0,4]="${TSC_PRJG_VERSION[0,0]}"."${TSC_PRJG_VERSION[0,1]}"."${TSC_PRJG_VERSION[0,2]}"-"${TSC_PRJG_VERSION[0,3]}"
TSC_PRJG_VERSION[1,4]="${TSC_PRJG_VERSION[1,0]}"."${TSC_PRJG_VERSION[1,1]}"."${TSC_PRJG_VERSION[1,2]}"-"${TSC_PRJG_VERSION[1,3]}"
TSC_PRJG_VERSION[2,4]="${TSC_PRJG_VERSION[2,0]}"."${TSC_PRJG_VERSION[2,1]}"."${TSC_PRJG_VERSION[2,2]}"-"${TSC_PRJG_VERSION[2,3]}"

if [ $TSC_DEBUG -ne "0" ]; then
for ((x=0; x<3; x++))
do
	for ((y=0; y<7; y++))
	do
		echo TSC_PRJG_VERSION[$x,$y]="${TSC_PRJG_VERSION[$x,$y]}"
	done
done
fi

TSC_PRJG_DEVELOP_VERSION=$TSC_PRJG_DEVEL

# CDN = config directory names

TSC_CDN_CLI="cli"
TSC_CDN_DOC="doc"
TSC_CDN_DOCDEVEL="develdoc"
TSC_CDN_DOCUSER="userdoc"
TSC_CDN_GUI="gui"
TSC_CDN_HW="hardware"
TSC_CDN_INCL="include"
TSC_CDN_INSTALL="install"
TSC_CDN_LIB="lib"
TSC_CDN_RPM="rpm"
TSC_CDN_SNAPYAML="snap"
TSC_CDN_SPEC="spec"
TSC_CDN_SRC="src"
TSC_CDN_SRPM="srpm"
TSC_CDN_TGZ="tgz"
TSC_CDN_LIBSYMBIOT="libsymbiot"

# CDPA = config directory path absolute and relative to configure

TSC_CDPA_PROJ=`pwd`
TSC_CDPR_PROJ=""
TSC_CDPA_CONF=$TSC_CDPA_PROJ
TSC_CDPR_CONF=$TSC_CDPR_PROJ

#####def####

# CFG = config file names

TSC_CFN_CFG="configure.sh"
TSC_CFN_CMK="config.mk"
TSC_CFN_CH="config.h"
TSC_CFN_LIBSYMBIOT="libsymbiot"
TSC_CFN_MF="Makefile"
TSC_CFN_MK=$TSC_CFN_MF
TSC_CTY_SNAPYAML="snapcraft.yaml"
TSC_CTY_SPEC="spec"
TSC_CPFN_SNAPYAML=""
TSC_CPFN_SPEC=""
TSC_CPFN_CMK=""
TSC_CPFN_CH=""

# SPB = system depended binaries with path

TSC_SBP_AR=`which ar`" -rs"
TSC_SBP_BASH=`which bash`
TSC_SBP_BISON=`which bison`
TSC_SBP_CC=`which gcc`
TSC_SBP_CP=`which cp`
TSC_SBP_CPP=`which c++`
TSC_SBP_DOT=`which dot`
TSC_SBP_ECHO=`which echo`
TSC_SBP_ECHOE=`which echo`" -e"
TSC_SBP_LEX=`which flex`
TSC_SBP_MK=`which make`
TSC_SBP_MKDIR=`which mkdir`
TSC_SBP_RM=`which rm`" -f"
TSC_SBP_RMDIR=`which rmdir`
TSC_SBP_RMDIRI=`which rmdir`" --ignore-fail-on-non-empty"
TSC_SBP_YACC=$TSC_SBP_BISON

# linker and compiler flags

CFLAGS_GLIB=`pkg-config --cflags glib-2.0 pango cairo gdk-pixbuf-2.0`" -I /usr/include -I /usr/lib64 -I "$TSC_CDPA_INCL
CFLAGS_GTK=`pkg-config --cflags gtk+-3.0 pango cairo gdk-pixbuf-2.0`"-I /usr/include -I /usr/lib64 -I "$TSC_CDPA_INCL
LIBS_GLIB=`pkg-config --libs glib-2.0`" -L /usr/lib -L /usr/lib64 -L "$TSC_CDPA_LIB" -lglib-2.0 -lsymbiot"
LIBS_GTK=`pkg-config --libs gtk+-3.0`" -L /usr/lib"

for ((z=0; z<3; z++))
do
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_DOC
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_INCL
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_INSTALL
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_GUI
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_LIBSYMBIOT
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_LIB
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_RPM
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_SNAPYAML
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_SPEC
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_SRC
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_SRPM
	$TSC_SBP_MKDIR -p $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$z,5]}$TSC_SLASH$TSC_CDN_TGZ
done

# parameter assignment
# $1 start remark line
# $2 language
# $3 assignment operator or empty


function tsc_write_spec(){
	$TSC_SBP_ECHOE "write" $4 "for ("$2")"
	$TSC_SBP_ECHOE $1"\n"$1" Spec-File("$2") for "$2"\n"$1 > $4
	$TSC_SBP_ECHOE "Summary: "$TSC_PRJG_PSUMS "("$2")" >> $4
	$TSC_SBP_ECHOE "Version: "$TSC_SPEC_VERSION >> $4
	$TSC_SBP_ECHOE "Release: "$TSC_SPEC_RELEASE >> $4
	$TSC_SBP_ECHOE "License: "$TSC_PRJG_PLIC >> $4
	$TSC_SBP_ECHOE "Group: "$TSC_PRJG_PGRP >> $4
	$TSC_SBP_ECHOE "Source: https://github.com/Chartwalker/${TSC_SPEC_TGZ}" >> $4
	$TSC_SBP_ECHOE "URL: https://github.com/Chartwalker/${TSC_SPEC_URL}" >> $4
	$TSC_SBP_ECHOE "\n%description: see manual pdf at https://github.com/Chartwalker/${TSC_SPEC_DOC}" >> $4

}

# parameter assignment
# $1 start remark line
# $2 language
# $3 assignment operator or empty


function tsc_write_snapyaml(){
	$TSC_SBP_ECHOE "write" $4 "for ("$2")"
	$TSC_SBP_ECHOE "name: "$TSC_PRJG_FNAME > $4
	$TSC_SBP_ECHOE "base: core24" >> $4
	$TSC_SBP_ECHOE "version: "${TSC_SNAPYAML_VERSION} >> $4
	$TSC_SBP_ECHOE "summary: "$TSC_PRJG_PSUMS >> $4
	$TSC_SBP_ECHOE "description: |" >> $4
	$TSC_SBP_ECHOE "  "$TSC_PRJG_PSUML >> $4
	$TSC_SBP_ECHOE "grade: "${TSC_SNAPYAML_GRADE} >> $4
	$TSC_SBP_ECHOE "confinement: "${TSC_SNAPYAML_CONFINEMENT} >> $4
}

# parameter assignment for writing files

# $1 start definition line #define or empty
# $2 start remark line
# $3 start action line
# $4 assignment operator or empty
# $5 outputfile

function tsc_write_env(){

# console redirected write

# create dirs relative to configure - no error if exist

	$TSC_SBP_ECHOE "write $5 for ("$TSC_PRJG_LANG")"
	
	$TSC_SBP_ECHOE "\n"$2" "$TSC_PRJG_COPYR > $5
	$TSC_SBP_ECHOE "\n"$2" "$TSC_PRJG_COMP >> $5
	$TSC_SBP_ECHOE "\n"$2" "$TSC_PRJG_DEDIT >> $5

	$TSC_SBP_ECHOE "\n"$2" DBG = debug defines" >> $5
	$TSC_SBP_ECHOE $1"TSC_DBG_LANG"$4$TSC_DBG_LANG  >> $5

	$TSC_SBP_ECHOE "\n"$2" SYS = system depended - hint: the sorting of uname is like the manpage uname --help" >> $5
	
	$TSC_SBP_ECHOE "\n"$1"TSC_SYS_ALL$4"$TSC_SYS_ALL >> $5
	$TSC_SBP_ECHOE $1"TSC_SYS_OPNS$4"$TSC_SYS_OPNS >> $5	
	$TSC_SBP_ECHOE $1"TSC_SYS_NODE$4"$TSC_SYS_NODE >> $5
	$TSC_SBP_ECHOE $1"TSC_SYS_OPREL$4"$TSC_SYS_OPREL >> $5
	$TSC_SBP_ECHOE $1"TSC_SYS_OPVER$4"$TSC_SYS_OPVER >> $5
	$TSC_SBP_ECHOE $1"TSC_SYS_ARCH$4"$TSC_SYS_ARCH >> $5
	$TSC_SBP_ECHOE $1"TSC_SYS_CPU$4"$TSC_SYS_CPU >> $5
	$TSC_SBP_ECHOE $1"TSC_SYS_HARDW$4"$TSC_SYS_HARDW >> $5
	$TSC_SBP_ECHOE $1"TSC_SYS_OPNL$4"$TSC_SYS_OPNL >> $5
	$TSC_SBP_ECHOE $1"TSC_SLASH$4"$TSC_SLASH >> $5

	$TSC_SBP_ECHOE "\n"$2" PRJG = project global settings - name of the game :-) as strings" >> $5

	$TSC_SBP_ECHOE "\n"$1"TSC_PRJG_LEVEL$4"$TSC_PRJG_LEVEL >> $5
	$TSC_SBP_ECHOE $1"TSC_PRJG_LANG"$4$TSC_PRJG_LANG  >> $5
	$TSC_SBP_ECHOE $1"TSC_LOG_LANG"$4$TSC_LOG_LANG  >> $5
	$TSC_SBP_ECHOE $1"__TSC_PRJG_LANG_DE__"$4$TSC_PRJG_LANG_DE  >> $5
	$TSC_SBP_ECHOE $1"__TSC_PRJG_LANG_EN__"$4$TSC_PRJG_LANG_EN  >> $5

	$TSC_SBP_ECHOE "\n"$1"TSC_PRJG_LEVEL$4"$TSC_PRJG_LEVEL >> $5
	$TSC_SBP_ECHOE $1"TSC_PRJG_PSUMS$4"$TSC_PRJG_PSUMS >> $5
	$TSC_SBP_ECHOE $1"TSC_PRJG_PSUML$4"$TSC_PRJG_PSUML >> $5
	$TSC_SBP_ECHOE $1"TSC_PRJG_PGRP$4"$TSC_PRJG_PGRP >> $5
	$TSC_SBP_ECHOE $1"TSC_PRJG_PLIC$4"$TSC_PRJG_PLIC >> $5


	$TSC_SBP_ECHOE "\n"$1"TSC_PRJG_TS$4"$TSC_PRJG_TS >> $5
	$TSC_SBP_ECHOE $1"TSC_PRJG_TS_S$4"$TSC_PRJG_TS_S >> $5

	$TSC_SBP_ECHOE "\n"$1"TSC_PRJG_COMP_S$4"$TSC_PRJG_COMP_S >> $5

	$TSC_SBP_ECHOE "\n"$1"TSC_PRJG_FNAME$4"$TSC_PRJG_FNAME >> $5
	$TSC_SBP_ECHOE $1"TSC_PRJG_PNAME$4"$TSC_PRJG_PNAME >> $5

	$TSC_SBP_ECHOE "\n"$1"TSC_PRJG_LANG_DE$4"$TSC_PRJG_LANG_DE >> $5
	$TSC_SBP_ECHOE $1"TSC_PRJG_LANG_EN$4"$TSC_PRJG_LANG_EN >> $5

	$TSC_SBP_ECHOE "\n"$2" PRJG = project global version settings" >> $5

	for ((x=0; x<3; x++))
	do
		$TSC_SBP_ECHOE "\n"$1"TSC_PRJG_"${TSC_PRJG_VERSION[$x,6]}"_MAJOR$4"${TSC_PRJG_VERSION[$x,0]} >> $5
		$TSC_SBP_ECHOE $1"TSC_PRJG_"${TSC_PRJG_VERSION[$x,6]}"_MINOR$4"${TSC_PRJG_VERSION[$x,1]} >> $5
		$TSC_SBP_ECHOE $1"TSC_PRJG_"${TSC_PRJG_VERSION[$x,6]}"_RELEASE$4"${TSC_PRJG_VERSION[$x,2]} >> $5
		$TSC_SBP_ECHOE $1"TSC_PRJG_"${TSC_PRJG_VERSION[$x,6]}"_PATCH$4"${TSC_PRJG_VERSION[$x,3]} >> $5
		$TSC_SBP_ECHOE $1"TSC_PRJG_"${TSC_PRJG_VERSION[$x,6]}"_VERSION$4"${TSC_PRJG_VERSION[$x,4]} >> $5
		$TSC_SBP_ECHOE $1"TSC_PRJG_"${TSC_PRJG_VERSION[$x,6]}"_VERSION_S$4""\"${TSC_PRJG_VERSION[$x,4]}"\" >> $5
done

	$TSC_SBP_ECHOE "\n"$2" CFN = config file names" >> $5

	$TSC_SBP_ECHOE "\n"$1"TSC_CFN_CFG$4"$TSC_CFN_CFG>> $5	
	$TSC_SBP_ECHOE $1"TSC_CFN_CMK$4"$TSC_CFN_CMK>> $5
	$TSC_SBP_ECHOE $1"TSC_CFN_CH$4"$TSC_CFN_CH >> $5
	$TSC_SBP_ECHOE $1"TSC_CFN_LIBSYMBIOT$4"$TSC_CFN_LIBSYMBIOT >> $5
	$TSC_SBP_ECHOE $1"TSC_CFN_MF$4"$TSC_CFN_MF >> $5

	$TSC_SBP_ECHOE "\n"$2"####write####""\n" >> $5
	for ((x=0; x<3; x++))
	do
		$TSC_SBP_ECHOE $1"TSC_CFN_"${TSC_PRJG_VERSION[$x,6]}"_SNAPYAML$4"$TSC_PRJG_FNAME-${TSC_PRJG_VERSION[$x,4]}"-"$TSC_CTY_SNAPYAML >> $5
		$TSC_SBP_ECHOE $1"TSC_CFN_"${TSC_PRJG_VERSION[$x,6]}"_SPEC$4"$TSC_PRJG_FNAME-${TSC_PRJG_VERSION[$x,4]}$TSC_CTY_SNAPYAML >> $5
	done
	
	$TSC_SBP_ECHOE "\n"$2" config directory path absolute and relative to configure""\n" >> $5
    for ((x=0; x<3; x++))
	do
		$TSC_SBP_ECHOE $1"TSC_CDPA_"${TSC_PRJG_VERSION[$x,6]}"_CONF$4"$TSC_CDPA_PROJ$TSC_SLASH$TSC_CDPA_CONF_${TSC_PRJG_VERSION[$x,5]} >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_CONF$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]} >> $5
	done
	
	$TSC_SBP_ECHOE "\n"$2" config directory path relative" >> $5
	for ((x=0; x<3; x++))
	do
		$TSC_SBP_ECHOE "\n"$1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_DOC$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_DOC >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_INCL$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_INCL >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_INSTALL$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_INSTALL >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_GUI$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_GUI >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_LIBSYMBIOT$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_LIBSYMBIOT >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_LIB$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_LIB >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_RPM$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_RPM >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_SNAPYAML$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_SNAPYAML >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_SPEC$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_SPEC >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_SRC$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_SRC >> $5
		$TSC_SBP_ECHOE $1"TSC_CDPR_"${TSC_PRJG_VERSION[$x,6]}"_SRPM$4"$TSC_CDPR_CONF${TSC_PRJG_VERSION[$x,5]}$TSC_SLASH$TSC_CDN_SRPM >> $5
	done
	
	$TSC_SBP_ECHOE "\n"$2" SPB = system depended binary with path" >> $5


	$TSC_SBP_ECHOE "\n"$1"TSC_SBP_AR$4"$TSC_SBP_AR >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_BASH$4"$TSC_SBP_BASH >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_BISON$4"$TSC_SBP_BISON >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_CC$4"$TSC_SBP_CC >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_CP$4"$TSC_SBP_CP >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_CPP$4"$TSC_SBP_CPP >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_DOT$4"$TSC_SBP_DOT >> $5
	$TSC_SBP_ECHO $1"TSC_SBP_ECHO$4"$TSC_SBP_ECHO >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_ECHOE$4"$TSC_SBP_ECHOE >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_LEX$4"$TSC_SBP_LEX >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_MK$4"$TSC_SBP_MK >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_MKDIR$4"$TSC_SBP_MKDIR >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_RM$4"$TSC_SBP_RM >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_RMDIR$4"$TSC_SBP_RMDIR >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_RMDIRI$4"$TSC_SBP_RMDIRI >> $5
	$TSC_SBP_ECHOE $1"TSC_SBP_YACC$4"$TSC_SBP_YACC >> $5

	$TSC_SBP_ECHOE "\n"$2" linker and compiler flags" >> $5

	$TSC_SBP_ECHOE "\n"$1"CFLAGS_GLIB$4"$CFLAGS_GLIB >> $5
	$TSC_SBP_ECHOE $1"CFLAGS_GTK$4"$CFLAGS_GTK >> $5
	$TSC_SBP_ECHOE $1"LIBS_GLIB$4"$LIBS_GLIB >> $5
	$TSC_SBP_ECHOE $1"LIBS_GTK$4"$LIBS_GTK >> $5

}
# parameter assignment for writing files

# $1 start definition line #define or empty
# $2 start remark line
# $3 start action line
# $4 assignment operator or empty
# $5 outputfile

for ((y=0; y<3; y++))
do
	tsc_write_env "" "#" "" "=" $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$y,5]}$TSC_SLASH$TSC_CFN_CMK
	tsc_write_env "#define " "//" " " " " $TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$y,5]}$TSC_SLASH$TSC_CFN_CH
done

for ((i=0; i<3; i++))
do 
	TSC_CPFN_CMK="$TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$i,5]}$TSC_SLASH$TSC_CFN_CMK"	
	TSC_CPFN_CH="$TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$i,5]}$TSC_SLASH$TSC_CFN_CH"


	TSC_PACK_VERSION="$TSC_PROJG_${TSC_PRJG_VERSION[$i,4]}"

	for ((j=0; j<3; j++))
	do
		TSC_SPEC_VERSION="$TSC_PROJG_${TSC_PRJG_VERSION[$j,0]}.${TSC_PRJG_VERSION[$j,1]}"
		TSC_SPEC_RELEASE="$TSC_PROJG_${TSC_PRJG_VERSION[$j,2]}-${TSC_PRJG_VERSION[$j,3]}"
		TSC_SPEC_TGZ="${TSC_PRJG_FNAME}${TSC_CDRA_CONF}${TSC_SLASH}${TSC_PRJG_VERSION[$j,5]}$TSC_SLASH$TSC_CDN_TGZ$TSC_SLASH${TSC_PRJG_FNAME}-${TSC_PRJG_VERSION[$j,4]}.src.tgz"
		TSC_SPEC_URL="${TSC_PRJG_FNAME}${TSC_CDRA_CONF}$TSC_SLASH${TSC_PRJG_VERSION[$j,5]}"
		TSC_SPEC_DOC="${TSC_PRJG_FNAME}${TSC_CDRA_CONF}$TSC_SLASH${TSC_PRJG_VERSION[$j,5]}$TSC_SLASH$TSC_CDN_DOC$TSC_SLASH${TSC_PRJG_FNAME}-${TSC_PRJG_VERSION[$j,4]}.pdf"

		TSC_CPFN_SPEC="$TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$i,5]}$TSC_SLASH$TSC_CDN_SPEC$TSC_SLASH${TSC_PRJG_FNAME}-${TSC_PRJG_VERSION[$j,4]}.${TSC_CTY_SPEC}"
		tsc_write_spec "#" $TSC_PRJG_LANG " " ${TSC_CPFN_SPEC}

		TSC_SNAPYAML_VERSION="$TSC_PROJG_${TSC_PRJG_VERSION[$j,4]}"
		TSC_SNAPYAML_GRADE="$TSC_PROJG_${TSC_PRJG_VERSION[$j,7]}"
		TSC_SNAPYAML_CONFINEMENT="$TSC_PROJG_${TSC_PRJG_VERSION[$j,8]}"
		
		TSC_CPFN_SNAPYAML="$TSC_CDPA_CONF$TSC_SLASH${TSC_PRJG_VERSION[$i,5]}$TSC_SLASH$TSC_CDN_SNAPYAML$TSC_SLASH${TSC_PRJG_FNAME}-${TSC_PRJG_VERSION[$j,4]}.${TSC_CTY_SNAPYAML}"
		tsc_write_snapyaml "#" $TSC_PRJG_LANG " " ${TSC_CPFN_SNAPYAML}

		$TSC_SBP_ECHOE "\nTSC_PROJG_${TSC_PRJG_VERSION[$j,6]}_SPEC="$TSC_CPFN_SPEC >> $TSC_CPFN_CMK
		$TSC_SBP_ECHOE "TSC_PROJG_${TSC_PRJG_VERSION[$j,6]}_SNAPYAML="$TSC_CPFN_SNAPYAML >> $TSC_CPFN_CMK

		$TSC_SBP_ECHOE "\n#define TSC_PROJG_${TSC_PRJG_VERSION[$j,6]}_SPEC "$TSC_CPFN_SPEC >> $TSC_CPFN_CH
		$TSC_SBP_ECHOE "#define TSC_PROJG_${TSC_PRJG_VERSION[$j,6]}_SNAPYAML "$TSC_CPFN_SNAPYAML >> $TSC_CPFN_CH
	done
		
		$TSC_SBP_ECHOE "\nTSC_CPFN_CMK=$TSC_CPFN_CMK" >> $TSC_CPFN_CMK
		$TSC_SBP_ECHOE "TSC_CPFN_CH=$TSC_CPFN_CH\n" >> $TSC_CPFN_CMK
		$TSC_SBP_ECHOE "\n#define TSC_CPFN_CMK $TSC_CPFN_CMK" >> $TSC_CPFN_CH
		$TSC_SBP_ECHOE "#define TSC_CPFN_CH $TSC_CPFN_CH\n" >> $TSC_CPFN_CH

done 
