include config.mk

.PHONY: clean all test install stable config

all: ;
ifeq ($(TSC_MAKE_DEBUG),1)
	${TSC_SILENT_MAKE}${TSC_SBP_ECHOE} "make all"
endif

install: ;
	${TSC_SILENT_MAKE}${TSC_SBP_ECHOE} "make install"

clean: ;
	${TSC_SILENT_MAKE}${TSC_SBP_ECHOE} "make clean"

test: ;
	${TSC_SILENT_MAKE}${TSC_SBP_ECHOE} "make test"

stable: ;
	${TSC_SILENT_MAKE}${TSC_SBP_ECHOE} "make stable"
